### ISSUE TITLE
Mô hình

### ISSUE THREAD

**Issue by DatNgoBK** [dangvansam98/demo_vietasr#1]
Cho mình hỏi chút, bạn đang dùng mô hình jasper của Nvidia à? demo này train bao nhiêu giờ dữ liệu và wer đang bao nhiêu vậy bạn? 
Thanks!

**Comment by dangvansam98** [comment]
Model được train trên bộ dữ liệu tổng hợp từ nhiều nguồn khoảng 200h bạn ạ. Còn wer thì được đánh giá trên bộ dữ liệu riêng nên cũng k so sánh được
